#!/usr/bin/env python3
"""
build_gallery_from_drive.py
Auto-generate gallery-data.js for the GCETTS gallery from shared Google Drive folders.

WHAT YOU NEED (one-time, free):
  1. A Google API key:
       https://console.cloud.google.com  ->  APIs & Services
       -> enable "Google Drive API"  -> Credentials -> Create credentials -> API key
  2. Each event = one Drive FOLDER, shared "Anyone with the link: Viewer".
     Put its share URL (or id) below. Photos inside should also be viewable
     (sharing the folder as "anyone with link" usually covers the contents).

THEN:
  - Fill in API_KEY and EVENTS below.
  - Run:  python3 build_gallery_from_drive.py
  - It writes gallery-data.js next to gallery.html. Done — reload the page.

No OAuth, no libraries beyond the Python standard library.
"""

import json, os, re, sys, urllib.parse, urllib.request

# ----------------------------------------------------------------------
API_KEY = os.environ.get("GALLERY_DRIVE_API_KEY", "PASTE_YOUR_GOOGLE_API_KEY_HERE")

# id: short slug · title: shown on the card · date: free text · featured: one True
# folder: the Drive folder share URL or just its id
EVENTS = [
    {"id":"texavision",  "title":"TEXAVISION — Annual Fest", "date":"January",
     "featured":True,  "blurb":"The institute's flagship annual festival.",
     "folder":"https://drive.google.com/drive/folders/PASTE_FOLDER_ID"},
    {"id":"convocation", "title":"Convocation & Farewell",   "date":"Academic Year",
     "featured":False, "blurb":"Celebrating our graduating batches.",
     "folder":"PASTE_FOLDER_ID"},
    # add more events here...
]

USE_FILENAME_AS_CAPTION = False   # set True to caption each photo with its file name
OUTFILE = "gallery-data.js"
# ----------------------------------------------------------------------

API = "https://www.googleapis.com/drive/v3/files"

def folder_id(s):
    m = re.search(r"/folders/([A-Za-z0-9_-]+)", s) or re.search(r"[?&]id=([A-Za-z0-9_-]+)", s)
    return m.group(1) if m else s.strip()

def clean_caption(name):
    stem = re.sub(r"\.(jpe?g|png|webp|gif)$", "", name, flags=re.I)
    return re.sub(r"[_\-]+", " ", stem).strip()

def list_images(fid):
    photos, token = [], None
    q = f"'{fid}' in parents and mimeType contains 'image/' and trashed = false"
    while True:
        params = {
            "q": q, "key": API_KEY, "pageSize": "1000",
            "fields": "nextPageToken,files(id,name)",
            "orderBy": "name_natural",
            "supportsAllDrives": "true", "includeItemsFromAllDrives": "true",
        }
        if token: params["pageToken"] = token
        url = API + "?" + urllib.parse.urlencode(params)
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                data = json.load(r)
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "ignore")
            sys.exit(f"\nDrive API error {e.code} for folder {fid}:\n{body}\n"
                     "Check: API key valid? Drive API enabled? Folder shared 'anyone with link'?")
        for f in data.get("files", []):
            ph = {"drive": f["id"]}
            if USE_FILENAME_AS_CAPTION:
                ph["cap"] = clean_caption(f["name"])
            photos.append(ph)
        token = data.get("nextPageToken")
        if not token:
            break
    return photos

def main():
    if "PASTE_YOUR" in API_KEY:
        sys.exit("Please set API_KEY at the top of this script.")
    out = []
    for ev in EVENTS:
        fid = folder_id(ev["folder"])
        if "PASTE_FOLDER" in fid:
            print(f"  skipping '{ev['id']}' (folder not set)"); continue
        print(f"  fetching '{ev['id']}' ...", end=" ", flush=True)
        photos = list_images(fid)
        print(f"{len(photos)} photos")
        if not photos:
            continue
        out.append({
            "id": ev["id"], "title": ev["title"], "date": ev.get("date",""),
            "featured": bool(ev.get("featured")), "blurb": ev.get("blurb",""),
            "cover": photos[0], "photos": photos,
        })
    if not out:
        sys.exit("No events with photos — nothing written.")
    js = ("// AUTO-GENERATED by build_gallery_from_drive.py — do not edit by hand.\n"
          "window.GALLERY_DATA = " + json.dumps(out, indent=2, ensure_ascii=False) + ";\n")
    with open(OUTFILE, "w", encoding="utf-8") as f:
        f.write(js)
    total = sum(len(e["photos"]) for e in out)
    print(f"\nWrote {OUTFILE}: {len(out)} albums, {total} photos. Reload gallery.html.")

if __name__ == "__main__":
    main()
