#!/usr/bin/env python3
"""
build_notices_from_drive.py
Generate notices-data.js from two shared Google Drive folders:
one for Notices/Circulars and one for Tenders. Files are listed newest-first
(by last-modified date). The site reads the result via drive-feed.js.

SETUP (same free API key as the gallery importer):
  1. Google Cloud console -> enable "Google Drive API" -> create an API key.
  2. Put your Notices folder and Tenders folder below (share each
     "Anyone with the link: Viewer").
  3. Provide the key by either:
       export DRIVE_API_KEY=xxxx        (recommended / used by CI)
     or paste it into API_KEY below.
  4. Run:  python3 build_notices_from_drive.py
     -> writes notices-data.js next to the html files. Reload the site.

Stdlib only; no external packages.
"""

import json, os, re, sys, urllib.parse, urllib.request

# ---------------------------------------------------------------- config
API_KEY = os.environ.get("DRIVE_API_KEY") or os.environ.get("GALLERY_DRIVE_API_KEY") or "PASTE_YOUR_GOOGLE_API_KEY_HERE"

NOTICES_FOLDER = "https://drive.google.com/drive/folders/1-CXEKcmNiBuNlb9o8iLm7AfXJRqe9rqs"
TENDERS_FOLDER = "https://drive.google.com/drive/folders/1Bva2MoWE8dkZj0-W7J_q2VxghJw4O6j2"

OUTFILE = "notices-data.js"
# ------------------------------------------------------------------------

API = "https://www.googleapis.com/drive/v3/files"

def folder_id(s):
    m = re.search(r"/folders/([A-Za-z0-9_-]+)", s) or re.search(r"[?&]id=([A-Za-z0-9_-]+)", s)
    return m.group(1) if m else s.strip()

def kind_of(mt):
    mt = (mt or "").lower()
    if "pdf" in mt: return "pdf"
    if "spreadsheet" in mt or "excel" in mt or "csv" in mt: return "sheet"
    if "presentation" in mt or "powerpoint" in mt: return "slide"
    if "document" in mt or "msword" in mt or "word" in mt: return "doc"
    if "image" in mt: return "image"
    if "folder" in mt: return "folder"
    return "file"

def list_folder(fid):
    items, token = [], None
    q = f"'{fid}' in parents and trashed = false"
    while True:
        params = {
            "q": q, "key": API_KEY, "pageSize": "1000",
            "fields": "nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink)",
            "orderBy": "modifiedTime desc",
            "supportsAllDrives": "true", "includeItemsFromAllDrives": "true",
        }
        if token: params["pageToken"] = token
        url = API + "?" + urllib.parse.urlencode(params)
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                data = json.load(r)
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "ignore")
            sys.exit(f"\nDrive API error {e.code} for folder {fid}:\n{body}\n"
                     "Check: key valid? Drive API enabled? folder shared 'anyone with link'?")
        for f in data.get("files", []):
            if kind_of(f.get("mimeType")) == "folder":
                continue
            items.append({
                "name": f.get("name", "Untitled"),
                "date": f.get("modifiedTime"),
                "url": f.get("webViewLink") or f"https://drive.google.com/file/d/{f['id']}/view",
                "kind": kind_of(f.get("mimeType")),
            })
        token = data.get("nextPageToken")
        if not token:
            break
    items.sort(key=lambda x: x["date"] or "", reverse=True)
    return items

def main():
    if "PASTE_YOUR" in API_KEY:
        sys.exit("Set DRIVE_API_KEY (env) or API_KEY in the script.")
    notices = [] if "PASTE_" in NOTICES_FOLDER else list_folder(folder_id(NOTICES_FOLDER))
    tenders = [] if "PASTE_" in TENDERS_FOLDER else list_folder(folder_id(TENDERS_FOLDER))
    js = ("// AUTO-GENERATED by build_notices_from_drive.py — do not edit by hand.\n"
          "window.NOTICES_DATA = " + json.dumps(notices, indent=2, ensure_ascii=False) + ";\n"
          "window.TENDERS_DATA = " + json.dumps(tenders, indent=2, ensure_ascii=False) + ";\n")
    with open(OUTFILE, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {OUTFILE}: {len(notices)} notices, {len(tenders)} tenders (newest first).")

if __name__ == "__main__":
    main()
