#!/usr/bin/env python3
"""
build_latestnews_from_drive.py
Generate latestnews-data.js from one Google Drive folder of images for the
homepage "Latest News" auto-scroll carousel. Each image's caption is its file
name without the extension. Images are listed newest-first.

SETUP (same free API key as the gallery / notices importers):
  1. Google Cloud console -> enable "Google Drive API" -> create an API key.
  2. Put your Latest-News image folder below (share it "Anyone with link: Viewer").
  3. Provide the key by either:
       export DRIVE_API_KEY=xxxx        (recommended / used by CI)
     or paste it into API_KEY below.
  4. Run:  python3 build_latestnews_from_drive.py
     -> writes latestnews-data.js next to the html files. Reload the site.

Stdlib only; no external packages.
"""

import json, os, re, sys, urllib.parse, urllib.request

# ---------------------------------------------------------------- config
API_KEY = os.environ.get("DRIVE_API_KEY") or os.environ.get("GALLERY_DRIVE_API_KEY") or "PASTE_YOUR_GOOGLE_API_KEY_HERE"

LATEST_NEWS_FOLDER = "https://drive.google.com/drive/folders/16TReQinH2DGYRvYvvlsRNhPCxZzLw4SQ"

OUTFILE = "latestnews-data.js"
# ------------------------------------------------------------------------

API = "https://www.googleapis.com/drive/v3/files"

def folder_id(s):
    m = re.search(r"/folders/([A-Za-z0-9_-]+)", s) or re.search(r"[?&]id=([A-Za-z0-9_-]+)", s)
    return m.group(1) if m else s.strip()

def strip_ext(name):
    return re.sub(r"\.[^.\/]+$", "", name or "")

def list_images(fid):
    items, token = [], None
    q = f"'{fid}' in parents and mimeType contains 'image/' and trashed = false"
    while True:
        params = {
            "q": q, "key": API_KEY, "pageSize": "1000",
            "fields": "nextPageToken,files(id,name,modifiedTime)",
            "orderBy": "modifiedTime desc",
            "supportsAllDrives": "true", "includeItemsFromAllDrives": "true",
        }
        if token: params["pageToken"] = token
        url = API + "?" + urllib.parse.urlencode(params)
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                data = json.load(r)
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "ignore")
            sys.exit(f"\nDrive API error {e.code} for folder {fid}:\n{body}\n"
                     "Check: key valid? Drive API enabled? folder shared 'anyone with link'?")
        for f in data.get("files", []):
            items.append({"drive": f["id"], "cap": strip_ext(f.get("name", ""))})
        token = data.get("nextPageToken")
        if not token:
            break
    return items

def main():
    if "PASTE_YOUR" in API_KEY:
        sys.exit("Set DRIVE_API_KEY (env) or API_KEY in the script.")
    images = [] if "PASTE_" in LATEST_NEWS_FOLDER else list_images(folder_id(LATEST_NEWS_FOLDER))
    js = ("// AUTO-GENERATED by build_latestnews_from_drive.py — do not edit by hand.\n"
          "// Each item: { drive:<file id>, cap:<file name without extension> }\n"
          "window.LATEST_NEWS_DATA = " + json.dumps(images, indent=2, ensure_ascii=False) + ";\n")
    with open(OUTFILE, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {OUTFILE}: {len(images)} images (newest first).")

if __name__ == "__main__":
    main()
