#!/usr/bin/env python3
"""
build_aicte_from_drive.py
Generate aicte-data.js by listing the AICTE EOA Reports Google Drive folder.
Files (and any sub-folders) added to the folder appear automatically the next
time this runs. The deploy workflow runs it on push and on a 6-hourly schedule,
so newly uploaded EOA letters show up on the site without any code change.

SETUP (same free API key as the gallery / notices importers):
  1. Google Cloud console -> enable "Google Drive API" -> create an API key.
  2. The folder is already set below (the institute's public AICTE EOA folder).
     Make sure it is shared "Anyone with link: Viewer".
  3. Provide the key by either:
       export DRIVE_API_KEY=xxxx        (recommended / used by CI)
     or paste it into API_KEY below.
  4. Run:  python3 build_aicte_from_drive.py
     -> writes aicte-data.js next to the html files.

Stdlib only; no external packages.
"""

import json, os, re, sys, urllib.parse, urllib.request

# ---------------------------------------------------------------- config
API_KEY = os.environ.get("DRIVE_API_KEY") or os.environ.get("GALLERY_DRIVE_API_KEY") or "PASTE_YOUR_GOOGLE_API_KEY_HERE"

# The institute's AICTE EOA Reports folder (already public).
AICTE_FOLDER = "https://drive.google.com/drive/folders/1fwgXa0EDTmuvWOG9Cj9W_0rtc5ZknU6D"

OUTFILE = "aicte-data.js"
# ------------------------------------------------------------------------

API = "https://www.googleapis.com/drive/v3/files"

def folder_id(s):
    m = re.search(r"/folders/([A-Za-z0-9_-]+)", s) or re.search(r"[?&]id=([A-Za-z0-9_-]+)", s)
    return m.group(1) if m else s.strip()

def kind_of(mt):
    mt = (mt or "").lower()
    if "folder" in mt: return "folder"
    if "pdf" in mt: return "pdf"
    if "spreadsheet" in mt or "excel" in mt or "csv" in mt: return "sheet"
    if "presentation" in mt or "powerpoint" in mt: return "slide"
    if "document" in mt or "msword" in mt or "word" in mt: return "doc"
    if "image" in mt: return "image"
    return "file"

def list_folder(fid):
    items, token = [], None
    q = f"'{fid}' in parents and trashed = false"
    while True:
        params = {
            "q": q, "key": API_KEY, "pageSize": "1000",
            "fields": "nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink)",
            "orderBy": "folder,modifiedTime desc",
            "supportsAllDrives": "true", "includeItemsFromAllDrives": "true",
        }
        if token: params["pageToken"] = token
        url = API + "?" + urllib.parse.urlencode(params)
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                data = json.load(r)
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "ignore")
            sys.exit(f"\nDrive API error {e.code} for folder {fid}:\n{body}\n"
                     "Check: key valid? Drive API enabled? folder shared 'anyone with link'?")
        for f in data.get("files", []):
            kind = kind_of(f.get("mimeType"))
            if kind == "folder":
                url_ = f"https://drive.google.com/drive/folders/{f['id']}"
            else:
                url_ = f.get("webViewLink") or f"https://drive.google.com/file/d/{f['id']}/view"
            items.append({
                "name": f.get("name", "Untitled"),
                "date": f.get("modifiedTime"),
                "url": url_,
                "kind": kind,
            })
        token = data.get("nextPageToken")
        if not token:
            break
    items.sort(key=lambda x: x["date"] or "", reverse=True)
    return items

def main():
    if "PASTE_YOUR" in API_KEY:
        sys.exit("Set DRIVE_API_KEY (env) or API_KEY in the script.")
    reports = [] if "PASTE_" in AICTE_FOLDER else list_folder(folder_id(AICTE_FOLDER))
    js = ("// AUTO-GENERATED by build_aicte_from_drive.py — do not edit by hand.\n"
          "window.AICTE_DATA = " + json.dumps(reports, indent=2, ensure_ascii=False) + ";\n")
    with open(OUTFILE, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"Wrote {OUTFILE}: {len(reports)} item(s) (newest first).")

if __name__ == "__main__":
    main()
