/* drive-feed.js — shared loader for Notices & Tenders.
   Loaded by index.html (ticker) and notices.html (full lists).

   Data source priority:
     1) window.NOTICES_DATA / window.TENDERS_DATA   (generated by build_notices_from_drive.py)
     2) live Drive fetch, IF you define:
          window.DRIVE_CONFIG = { apiKey:"...", noticesFolder:"<url-or-id>", tendersFolder:"<url-or-id>" }
        (use a referrer-restricted, Drive-API-only key; data must be "anyone with link")
     3) empty (UI then hides / shows an empty state)

   Each returned item: { id, name, date (ISO), url, kind }
   kind ∈ pdf | doc | sheet | slide | image | folder | file
*/
(function () {
  function folderId(s) {
    if (!s) return "";
    var m = String(s).match(/\/folders\/([A-Za-z0-9_-]+)/) || String(s).match(/[?&]id=([A-Za-z0-9_-]+)/);
    return m ? m[1] : String(s).trim();
  }
  function kindOf(mt) {
    mt = (mt || "").toLowerCase();
    if (mt.indexOf("pdf") >= 0) return "pdf";
    if (mt.indexOf("spreadsheet") >= 0 || mt.indexOf("excel") >= 0 || mt.indexOf("csv") >= 0) return "sheet";
    if (mt.indexOf("presentation") >= 0 || mt.indexOf("powerpoint") >= 0) return "slide";
    if (mt.indexOf("document") >= 0 || mt.indexOf("msword") >= 0 || mt.indexOf("word") >= 0) return "doc";
    if (mt.indexOf("image") >= 0) return "image";
    if (mt.indexOf("folder") >= 0) return "folder";
    return "file";
  }
  function normalize(f) {
    return {
      id: f.id,
      name: f.name,
      date: f.modifiedTime || f.createdTime || null,
      url: f.webViewLink || ("https://drive.google.com/file/d/" + f.id + "/view"),
      kind: kindOf(f.mimeType)
    };
  }
  function sortDesc(arr) {
    return (arr || []).slice().sort(function (x, y) {
      return String(y.date || "").localeCompare(String(x.date || ""));
    });
  }
  async function fetchFolder(apiKey, fid) {
    var files = [], token = null;
    do {
      var p = new URLSearchParams({
        q: "'" + fid + "' in parents and trashed = false",
        key: apiKey, pageSize: "1000",
        fields: "nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink)",
        orderBy: "modifiedTime desc",
        supportsAllDrives: "true", includeItemsFromAllDrives: "true"
      });
      if (token) p.set("pageToken", token);
      var r = await fetch("https://www.googleapis.com/drive/v3/files?" + p.toString());
      if (!r.ok) throw new Error("Drive API " + r.status);
      var d = await r.json();
      files = files.concat((d.files || []).map(normalize));
      token = d.nextPageToken;
    } while (token);
    return sortDesc(files);
  }

  window.DriveFeed = {
    folderId: folderId,
    load: async function () {
      var sNot = window.NOTICES_DATA, sTen = window.TENDERS_DATA, cfg = window.DRIVE_CONFIG;
      if (Array.isArray(sNot) || Array.isArray(sTen)) {
        return { notices: sortDesc(sNot || []), tenders: sortDesc(sTen || []), source: "static" };
      }
      if (cfg && cfg.apiKey && (cfg.noticesFolder || cfg.tendersFolder)) {
        var res = await Promise.all([
          cfg.noticesFolder ? fetchFolder(cfg.apiKey, folderId(cfg.noticesFolder)) : Promise.resolve([]),
          cfg.tendersFolder ? fetchFolder(cfg.apiKey, folderId(cfg.tendersFolder)) : Promise.resolve([])
        ]);
        return { notices: res[0], tenders: res[1], source: "live" };
      }
      return { notices: [], tenders: [], source: "none" };
    }
  };
})();
