/* drive-feed.js — shared loader for Notices & Tenders.
   Loaded by index.html (ticker) and notices.html (full lists).

   Data source priority:
     1) window.NOTICES_DATA / window.TENDERS_DATA   (generated by build_notices_from_drive.py)
     2) live Drive fetch, IF you define:
          window.DRIVE_CONFIG = { apiKey:"...", noticesFolder:"<url-or-id>", tendersFolder:"<url-or-id>" }
        (use a referrer-restricted, Drive-API-only key; data must be "anyone with link")
     3) empty (UI then hides / shows an empty state)

   Each returned item: { id, name, date (ISO), url, kind }
   kind ∈ pdf | doc | sheet | slide | image | folder | file
*/
(function () {
  function folderId(s) {
    if (!s) return "";
    var m = String(s).match(/\/folders\/([A-Za-z0-9_-]+)/) || String(s).match(/[?&]id=([A-Za-z0-9_-]+)/);
    return m ? m[1] : String(s).trim();
  }
  function kindOf(mt) {
    mt = (mt || "").toLowerCase();
    if (mt.indexOf("pdf") >= 0) return "pdf";
    if (mt.indexOf("spreadsheet") >= 0 || mt.indexOf("excel") >= 0 || mt.indexOf("csv") >= 0) return "sheet";
    if (mt.indexOf("presentation") >= 0 || mt.indexOf("powerpoint") >= 0) return "slide";
    if (mt.indexOf("document") >= 0 || mt.indexOf("msword") >= 0 || mt.indexOf("word") >= 0) return "doc";
    if (mt.indexOf("image") >= 0) return "image";
    if (mt.indexOf("folder") >= 0) return "folder";
    return "file";
  }
  function normalize(f) {
    return {
      id: f.id,
      name: f.name,
      date: f.modifiedTime || f.createdTime || null,
      url: f.webViewLink || ("https://drive.google.com/file/d/" + f.id + "/view"),
      kind: kindOf(f.mimeType)
    };
  }
  function sortDesc(arr) {
    return (arr || []).slice().sort(function (x, y) {
      return String(y.date || "").localeCompare(String(x.date || ""));
    });
  }
  async function fetchFolder(apiKey, fid) {
    var files = [], token = null;
    do {
      var p = new URLSearchParams({
        q: "'" + fid + "' in parents and trashed = false",
        key: apiKey, pageSize: "1000",
        fields: "nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink)",
        orderBy: "modifiedTime desc",
        supportsAllDrives: "true", includeItemsFromAllDrives: "true"
      });
      if (token) p.set("pageToken", token);
      var r = await fetch("https://www.googleapis.com/drive/v3/files?" + p.toString());
      if (!r.ok) throw new Error("Drive API " + r.status);
      var d = await r.json();
      files = files.concat((d.files || []).map(normalize));
      token = d.nextPageToken;
    } while (token);
    return sortDesc(files);
  }

  function driveImg(id, w){ return "https://drive.google.com/thumbnail?id=" + id + "&sz=w" + (w||1000); }
  function stripExt(n){ return (n||"").replace(/\.[^.\/]+$/, ""); }
  var IMG_WIDTHS = [400,800,1200,1600];
  function resolveImg(it, w){
    if (typeof it === "string") return { url:it, srcset:null, cap:"" };
    if (it.drive) return {
      url: driveImg(it.drive, w||1200),
      srcset: IMG_WIDTHS.map(function(x){ return driveImg(it.drive,x)+" "+x+"w"; }).join(", "),
      cap: it.cap || ""
    };
    return { url: it.url, srcset: it.srcset||null, cap: it.cap||"" };
  }
  async function fetchImages(apiKey, fid){
    var files = [], token = null;
    do {
      var p = new URLSearchParams({
        q: "'" + fid + "' in parents and mimeType contains 'image/' and trashed = false",
        key: apiKey, pageSize: "1000",
        fields: "nextPageToken,files(id,name,modifiedTime)",
        orderBy: "modifiedTime desc",
        supportsAllDrives: "true", includeItemsFromAllDrives: "true"
      });
      if (token) p.set("pageToken", token);
      var r = await fetch("https://www.googleapis.com/drive/v3/files?" + p.toString());
      if (!r.ok) throw new Error("Drive API " + r.status);
      var d = await r.json();
      files = files.concat((d.files || []).map(function(f){ return { drive:f.id, cap:stripExt(f.name) }; }));
      token = d.nextPageToken;
    } while (token);
    return files;
  }

  var _cache = null;
  window.DriveFeed = {
    folderId: folderId,
    resolveImg: resolveImg,
    load: function () {
      if (_cache) return _cache;             // memoize: many callers, one fetch
      _cache = (async function () {
        var cfg = window.DRIVE_CONFIG || {};
        var notices = [], tenders = [], source = "none";
        var sNot = window.NOTICES_DATA, sTen = window.TENDERS_DATA;
        if (Array.isArray(sNot) || Array.isArray(sTen)) {
          notices = sortDesc(sNot || []); tenders = sortDesc(sTen || []); source = "static";
        } else if (cfg.apiKey && (cfg.noticesFolder || cfg.tendersFolder)) {
          var res = await Promise.all([
            cfg.noticesFolder ? fetchFolder(cfg.apiKey, folderId(cfg.noticesFolder)) : Promise.resolve([]),
            cfg.tendersFolder ? fetchFolder(cfg.apiKey, folderId(cfg.tendersFolder)) : Promise.resolve([])
          ]);
          notices = res[0]; tenders = res[1]; source = "live";
        }
        // Latest News images (caption = file name without extension)
        var latestNews = [];
        if (Array.isArray(window.LATEST_NEWS_DATA)) {
          latestNews = window.LATEST_NEWS_DATA.map(function (x) { return resolveImg(x, 1200); });
        } else if (cfg.apiKey && cfg.latestNewsFolder) {
          try {
            var imgs = await fetchImages(cfg.apiKey, folderId(cfg.latestNewsFolder));
            latestNews = imgs.map(function (x) { return resolveImg(x, 1200); });
          } catch (e) { latestNews = []; }
        }
        // Research Highlights images (separate folder)
        var researchHighlights = [];
        if (Array.isArray(window.RESEARCH_HIGHLIGHTS_DATA)) {
          researchHighlights = window.RESEARCH_HIGHLIGHTS_DATA.map(function (x) { return resolveImg(x, 1200); });
        } else if (cfg.apiKey && cfg.researchHighlightsFolder) {
          try {
            var rimgs = await fetchImages(cfg.apiKey, folderId(cfg.researchHighlightsFolder));
            researchHighlights = rimgs.map(function (x) { return resolveImg(x, 1200); });
          } catch (e) { researchHighlights = []; }
        }
        return { notices: notices, tenders: tenders, latestNews: latestNews, researchHighlights: researchHighlights, source: source };
      })();
      return _cache;
    }
  };
})();
