#!/usr/bin/env python3
"""
optimize_images.py
Pre-resize local images into responsive variants for fast loading.

For every  foo.jpg  it creates  foo-400.jpg, foo-800.jpg, foo-1280.jpg
(only downscaling — never upscales) plus an optional .webp.
The gallery's srcset uses exactly these  <name>-<width>.<ext>  files.

USAGE:
    pip install pillow
    python3 optimize_images.py

AFTER RUNNING (to switch the gallery to local responsive images):
    add this one line to gallery-data.js (or a small <script> before gallery.html's app):
        window.GALLERY_RESPONSIVE_LOCAL = true;
    (Google Drive images are already responsive and need no flag.)
"""

import os, sys
try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required:  pip install pillow")

# (folder, [widths]) — widths to generate. Faculty avatars are small, so 2 sizes.
TARGETS = [
    ("assets/gallery",  [400, 800, 1280]),
    ("assets/faculty",  [124, 248]),
]
MAKE_WEBP = True
QUALITY   = 82
EXTS      = (".jpg", ".jpeg", ".png")
VARIANT   = __import__("re").compile(r"-\d+\.(jpe?g|png|webp)$", __import__("re").I)

def process(path, widths):
    stem, ext = os.path.splitext(path)
    made = 0
    try:
        with Image.open(path) as im:
            im = im.convert("RGB") if im.mode in ("P", "RGBA") else im
            w0 = im.width
            for w in widths:
                if w >= w0:        # never upscale
                    continue
                ratio = w / float(w0)
                size = (w, max(1, round(im.height * ratio)))
                resized = im.resize(size, Image.LANCZOS)
                out = f"{stem}-{w}{ext}"
                if not (os.path.exists(out) and os.path.getmtime(out) >= os.path.getmtime(path)):
                    resized.save(out, quality=QUALITY, optimize=True)
                    made += 1
                if MAKE_WEBP:
                    outw = f"{stem}-{w}.webp"
                    if not (os.path.exists(outw) and os.path.getmtime(outw) >= os.path.getmtime(path)):
                        resized.save(outw, "WEBP", quality=QUALITY)
                        made += 1
    except Exception as e:
        print("  ! skip", path, "->", e)
    return made

def main():
    grand = 0
    for folder, widths in TARGETS:
        if not os.path.isdir(folder):
            print(f"  (no {folder}/ — skipping)"); continue
        n = 0
        for root, _, files in os.walk(folder):
            for fn in files:
                if fn.lower().endswith(EXTS) and not VARIANT.search(fn):
                    n += process(os.path.join(root, fn), widths)
        print(f"  {folder}: generated/updated {n} files")
        grand += n
    print(f"\nDone. {grand} variant files written.")
    # Detect whether any responsive variants now exist, and write a flag file the
    # pages load automatically (no manual editing needed, locally or in CI).
    has_variant = False
    for folder, _ in TARGETS:
        if os.path.isdir(folder):
            for _root, _dirs, files in os.walk(folder):
                if any(VARIANT.search(f) for f in files):
                    has_variant = True; break
        if has_variant: break
    flag = "true" if has_variant else "false"
    with open("gallery-responsive.js", "w") as f:
        f.write("// auto-generated by optimize_images.py — do not edit by hand.\n"
                f"window.GALLERY_RESPONSIVE_LOCAL = {flag};\n")
    print(f"Wrote gallery-responsive.js (GALLERY_RESPONSIVE_LOCAL = {flag}).")

if __name__ == "__main__":
    main()
